### ISSUE TITLE
Short instruction how to run the project

### ISSUE THREAD

**Issue by Sharvadze** [darinkist/MediumArticle_InteractiveChatGPTSessionsInJupyterNotebook#4]
Thanks for the interesting concept, I'm struggling to launch the application. A short instruction how to do it would be super useful. Tried to run it through the JupyterLab without success, thanks

**Comment by darinkist** [comment]
What exactly are the error messages you are receiving?

**Comment by Sharvadze** [comment]
Got it sorted, thanks. Mainly the missing modules/libraries
